### ISSUE TITLE
New version breaks Dense Ores

### ISSUE THREAD

**Issue by Rudy2D2** [McJty/compatlayer#26]
Updating to the newest CompatLayer breaks Dense Ores:
com.rwtema.denseores.ProxyClient$1: Dense Ores requires CompatLayer to run in Minecraft 1.10.2

**Comment by josephcsible** [comment]
This is Dense Ores' fault. It's testing for CompatLayer a weird way instead of just putting `required-after:compatlayer` in its `dependencies` field. ~~Report this to them.~~ I opened rwtema/DenseOres#148 about this.

**Comment by Progamer1865** [comment]
Guys, you will need to use CompatLayer 0.3.1 along with DenseOres 1.0.2  worked for me. And also, if you use forge, it may be a crash due to Ram. In the launcher, go to Launch settings, click your profile you use for Forge, then enable JVM arguements. Delete the text. For four gigs of ram [what i do] type in
"-Xmx4096M -Xms4096M" [without quotes] three gigs of Ram will be "-Xmx3072M -Xms3072M" [without quotes], two gigs of Ram is "-Xmx2048M -Xms2048M" [without quotes], and one gigabite of Ram {default} is "-Xmx1024M -Xms1024M" [without quotes]. These are solutions to crashes as it worked for me. As I type this right now I have 28 mods loaded including Dense Ores so i gotta fly as Minecraft awaits. Good luck!
